# Generated by Django 4.1.3 on 2022-11-25 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_remove_advert_property_remove_booking_advert_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="property", name="adverts",),
        migrations.DeleteModel(name="Advert",),
        migrations.DeleteModel(name="Booking",),
    ]
