# Generated by Django 4.1.3 on 2022-11-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_advert_property_alter_booking_advert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="property",
            name="guest_limit",
            field=models.PositiveIntegerField(),
        ),
    ]
