# Generated by Django 4.1.3 on 2022-11-25 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_advert_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advert",
            name="property",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="properties.property",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="advert",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="properties.advert",
            ),
        ),
    ]
